// Copyright (c) 2019 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=357e86cb1c1767a78adc230cf194c3751dc7678f$
//

#include "libcef_dll/ctocpp/media_access_callback_ctocpp.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefMediaAccessCallbackCToCpp::Continue(int allowed_permissions) {
  cef_media_access_callback_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, cont))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->cont(_struct, allowed_permissions);
}

// CONSTRUCTOR - Do not edit by hand.

CefMediaAccessCallbackCToCpp::CefMediaAccessCallbackCToCpp() {}

template <>
cef_media_access_callback_t* CefCToCppRefCounted<
    CefMediaAccessCallbackCToCpp,
    CefMediaAccessCallback,
    cef_media_access_callback_t>::UnwrapDerived(CefWrapperType type,
                                                CefMediaAccessCallback* c) {
  NOTREACHED() << "Unexpected class type: " << type;
  return NULL;
}

#if DCHECK_IS_ON()
template <>
base::AtomicRefCount CefCToCppRefCounted<
    CefMediaAccessCallbackCToCpp,
    CefMediaAccessCallback,
    cef_media_access_callback_t>::DebugObjCt ATOMIC_DECLARATION;
#endif

template <>
CefWrapperType CefCToCppRefCounted<CefMediaAccessCallbackCToCpp,
                                   CefMediaAccessCallback,
                                   cef_media_access_callback_t>::kWrapperType =
    WT_MEDIA_ACCESS_CALLBACK;
